### ISSUE TITLE
Usage assistance

### ISSUE THREAD

**Issue by User-790** [1ucif3r/LockBit-Builder#1]
Hello there, I just had a couple questions on how to use this tool exactly, I am just confused as to what should happen after I execute the builder and keygen along with the .bat file. 

It is also displaying with the .bat file that "Public Key File Error" should I go forth and great my own public key?

**Comment by 1ucif3r** [comment]
just dm on discord i will show a demo there . Thanks . Discord : https://discord.gg/rzgpYA2w
